apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chronos-birthday-api.fullname" . }}-config
  labels:
    {{- include "chronos-birthday-api.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ include "chronos-birthday-api.databaseUrl" . | quote }}
