{{- if and .Values.postgresql .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    {{- include "chronos-birthday-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.auth.password | default "birthday_secret_password" | quote }}
{{- else if and .Values.externalDatabase (not .Values.externalDatabase.existingSecret) .Values.externalDatabase.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chronos-birthday-api.fullname" . }}-secret
  labels:
    {{- include "chronos-birthday-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.externalDatabase.password | quote }}
{{- end }}
